# Generated by Django 6.0.1 on 2026-01-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, help_text='[city name], [country name]', max_length=200, null=True),
        ),
    ]
